version: "3.3"
services:

  # Website container
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
#     platform: linux/amd64
    image: soufianeodf/website
    container_name: website
    networks:
      - frontend
    deploy:
      replicas: 1
    ports:
      - '80:80'

  # Zookeeper container
  zookeeper:
    image: zookeeper
    networks:
      - backend
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1

  # Apache Kafka container
  divolte-kafka:
    image: wurstmeister/kafka
    container_name: divolte-kafka
    networks:
      - backend
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: divolte-kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "tracking-avro:4:1,tracking-json:4:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://divolte-kafka:9092,INTERNAL://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  # Kafka Manager container
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    deploy:
      replicas: 1
    networks:
      - backend
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null

  # Divolte container
  docker-divolte:
    build:
      context: ./divolte-collector
      dockerfile: Dockerfile
#     platform: linux/amd64
    image: soufianeodf/divolte-collector
    container_name: docker-divolte
    networks:
      - frontend
      - backend
    deploy:
      replicas: 3
    restart: always
    environment:
      DIVOLTE_KAFKA_BROKER_LIST: divolte-kafka:9092
      DIVOLTE_KAFKA_TOPIC: tracking-avro
    ports:
      - 8290:8290
    depends_on:
      - divolte-kafka

  # Kafka streams container
  kafka-streams:
    build:
      context: ./kafka-streams-avro-to-json
      dockerfile: Dockerfile
#     platform: linux/amd64
    image: soufianeodf/kafka-streams
    container_name: kafka-streams
    networks:
      - backend
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - divolte-kafka

  # Apache Druid container
  apache-druid:
    build:
      context: ./druid
      dockerfile: Dockerfile
#     platform: linux/amd64
    image: soufianeodf/apache-druid
    container_name: apache-druid
    networks:
      - backend
    deploy:
      replicas: 1
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
      - 8888:8888
    depends_on:
      - divolte-kafka

  # Apache Superset container
  apache-superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
#     platform: linux/amd64
    image: soufianeodf/apache-superset
    container_name: superset
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == node1]
    restart: always
    ports:
      - 8080:8088

networks:
  frontend:
  backend:
