FROM nginx:latest

RUN apt-get update && apt-get install -y git \
	&& apt-get install vim \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /usr/share/nginx/html

COPY website/nginx.conf /etc/nginx/conf.d/default.conf

RUN git clone --branch main --single-branch --depth 1 https://github.com/soufianeodf/youtube-divolte-collector-with-apache-kafka.git divolte-with-kafka \
	&& cp -r divolte-with-kafka/website/* . \
	&& rm -rf divolte-with-kafka
