mapping {
  map eventParameter('country') onto 'country'
  map eventParameter('state') onto 'state'
  map eventParameter('city') onto 'city'
  map eventParameter('postal') onto 'postal'
  map eventParameter('latitude') onto 'latitude'
  map eventParameter('longitude') onto 'longitude'
  map eventParameter('ip') onto 'ip'
  map eventParameter('continent_code') onto 'continent_code'
  map eventParameter('continent_name') onto 'continent_name'
  map eventParameter('country_code') onto 'country_code'
  map eventParameter('region_code') onto 'region_code'
  map eventParameter('capital_city') onto 'capital_city'
  map eventParameter('language_code') onto 'language_code'
  map eventParameter('language_name') onto 'language_name'
  map eventParameter('country_flag_url') onto 'country_flag_url'
  map eventParameter('country_flag_emoji') onto 'country_flag_emoji'
  map eventParameter('browser_name') onto 'browser_name'
  map eventParameter('browser_full_version') onto 'browser_full_version'
  map eventParameter('browser_major_version') onto 'browser_major_version'
  map eventParameter('navigator_app_name') onto 'navigator_app_name'
  map eventParameter('navigator_user_agent') onto 'navigator_user_agent'
  map eventParameter('os_name') onto 'os_name'
}
